LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_ARCH), arm)
	#su binary
	include $(CLEAR_VARS)
	LOCAL_MODULE := su.recovery
	LOCAL_MODULE_TAGS := optional
	LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
	LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
	LOCAL_SRC_FILES := arm/su
	include $(BUILD_PREBUILT)
endif
ifeq ($(TARGET_ARCH), arm64)
	#su binary
	include $(CLEAR_VARS)
	LOCAL_MODULE := su.recovery
	LOCAL_MODULE_TAGS := optional
	LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
	LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
	LOCAL_SRC_FILES := arm64/su
	include $(BUILD_PREBUILT)
endif

ifeq ($(TARGET_ARCH), mips)
	#su binary
	include $(CLEAR_VARS)
	LOCAL_MODULE := su.recovery
	LOCAL_MODULE_TAGS := optional
	LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
	LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
	LOCAL_SRC_FILES := mips/su
	include $(BUILD_PREBUILT)
endif
ifeq ($(TARGET_ARCH), mips64)
	#su binary
	include $(CLEAR_VARS)
	LOCAL_MODULE := su.recovery
	LOCAL_MODULE_TAGS := optional
	LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
	LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
	LOCAL_SRC_FILES := mips64/su
	include $(BUILD_PREBUILT)
endif

ifeq ($(TARGET_ARCH), x86)
	#su binary
	include $(CLEAR_VARS)
	LOCAL_MODULE := su.recovery
	LOCAL_MODULE_TAGS := optional
	LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
	LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
	LOCAL_SRC_FILES := x86/su
	include $(BUILD_PREBUILT)
endif
ifeq ($(TARGET_ARCH), x64)
	#su binary
	include $(CLEAR_VARS)
	LOCAL_MODULE := su.recovery
	LOCAL_MODULE_TAGS := optional
	LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
	LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
	LOCAL_SRC_FILES := x64/su
	include $(BUILD_PREBUILT)
endif

#install-su.sh
include $(CLEAR_VARS)
LOCAL_MODULE := install-su.sh
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/sbin
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

#install-recovery.sh
include $(CLEAR_VARS)
LOCAL_MODULE := install-recovery.sh
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/etc
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)

#99SuperSUDaemon
include $(CLEAR_VARS)
LOCAL_MODULE := 99SuperSUDaemon
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := RECOVERY_EXECUTABLES
LOCAL_MODULE_PATH := $(TARGET_RECOVERY_ROOT_OUT)/etc
LOCAL_SRC_FILES := $(LOCAL_MODULE)
include $(BUILD_PREBUILT)
